spring.application.name=ecommerce-performance-tuning

# Server port
server.port=8081

# --- Database WITHOUT performance techniques (baseline) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/NonePerformanceTest
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Database WITH performance techniques (optimized) ---
app.datasource.optimized.url=jdbc:postgresql://localhost:5432/PerformanceTest
app.datasource.optimized.username=postgres
app.datasource.optimized.password=password
app.datasource.optimized.driver-class-name=org.postgresql.Driver

# Logging
logging.level.com.example=DEBUG